---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka1
  name: kafka1
spec:
  ports:
  - name: port-9092
    port: 9092
  selector:
    app: kafka1
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka2
  name: kafka2
spec:
  ports:
  - name: port-9092
    port: 9092
  selector:
    app: kafka2
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka3
  name: kafka3
spec:
  ports:
  - name: port-9092
    port: 9092
  selector:
    app: kafka3
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka1
  name: kafka1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka1
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka1:9092
        image: confluentinc/cp-kafka:latest
        name: kafka1
        ports:
        - containerPort: 9092
        resources: {}
      hostname: kafka1
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka2
  name: kafka2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka2
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka2:9092
        image: confluentinc/cp-kafka:latest
        name: kafka2
        ports:
        - containerPort: 9092
        resources: {}
      hostname: kafka2
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka3
  name: kafka3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka3
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka3:9092
        image: confluentinc/cp-kafka:latest
        name: kafka3
        ports:
        - containerPort: 9092
        resources: {}
      hostname: kafka3
      restartPolicy: Always
status: {}
